branch-defaults:
  master:
    environment: taskmaster-dev
    group_suffix: null
deploy:
  artifact: ./build/libs/taskmaster-0.0.1-SNAPSHOT.jar
global:
  application_name: taskmaster
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
